apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
  namespace: expense-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
        - name: api
          image: asrathod/expense-backend:2.2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
