
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-app-ingress
  namespace: expense-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
      host: "*"
        http:    
        paths:
           path: /
            pathType: Prefix
            backend:
              service:
                name: expense-web-svc
                port:
                  number: 80
           path: /api
            pathType: Prefix
            backend:
              service:
               name: expense-api-svc                
               port:
                  number: 8080


