
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-app-ingress
  namespace: expense-app
  annotations:
    # If you use the NGINX Ingress Controller; change if your controller is different
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "*"  # Match any host (useful for testing)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expense-web-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
               name: expense-api-svc
                port:

